// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh_dx66o35blXb__sMaKbZ6Gm_XG2pnFA',
    appId: '1:419250492719:web:9a9095aaedbf5a8e117dda',
    messagingSenderId: '419250492719',
    projectId: 'my-first-trial-project-a5dc3',
    authDomain: 'my-first-trial-project-a5dc3.firebaseapp.com',
    storageBucket: 'my-first-trial-project-a5dc3.firebasestorage.app',
    measurementId: 'G-HVPJCDFWJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClIhU9m_8sqgZa-ucVMTpjA60IUv5PLaY',
    appId: '1:419250492719:android:1bc2d64a0ac1e5d3117dda',
    messagingSenderId: '419250492719',
    projectId: 'my-first-trial-project-a5dc3',
    storageBucket: 'my-first-trial-project-a5dc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcc1wQ17zzMUPLwUfBjVwtzBDyYlY8DvE',
    appId: '1:419250492719:ios:19965c0bac4482e2117dda',
    messagingSenderId: '419250492719',
    projectId: 'my-first-trial-project-a5dc3',
    storageBucket: 'my-first-trial-project-a5dc3.firebasestorage.app',
    iosBundleId: 'com.example.myTrialFirstApp',
  );
}
